//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightningDisplay
{
    
    internal partial class Resources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resources.manager == null))
                {
                    Resources.manager = new System.Resources.ResourceManager("LightningDisplay.Resources", typeof(Resources).Assembly);
                }
                return Resources.manager;
            }
        }
        internal static string GetString(Resources.StringResources id)
        {
            return ((string)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(Resources.BinaryResources id)
        {
            return ((byte[])(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            LightningOff = -20565,
            LEDdecimal = -20271,
            LEDblank = -15536,
            LEDDigits = -10516,
            LEDorange = -9700,
            LEDDigitsGreen_sm = -5401,
            LightningOn = -3642,
            LEDred = 1515,
            wifi3 = 5535,
            wifi2 = 5536,
            wifi1 = 5537,
            wifi0 = 5538,
            wifi5 = 5541,
            wifi4 = 5542,
            LEDdecimalGreen_sm = 6307,
            LEDgreen = 28985,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            EnviroWindow = -9641,
            NetKeyWindow = -9267,
            wifiWindow = -5636,
            String1 = 1228,
            SettingsWindow = 3111,
            MenuWindow = 11803,
            MainWindow = 14107,
        }
    }
}
